-- Create a function to ensure client_points table exists
-- Run this in Supabase SQL Editor

CREATE OR REPLACE FUNCTION ensure_client_points_table()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  -- Create the table if it doesn't exist
  CREATE TABLE IF NOT EXISTS public.client_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    points INTEGER DEFAULT 0 NOT NULL,
    total_earned INTEGER DEFAULT 0 NOT NULL,
    total_redeemed INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id)
  );

  -- Enable RLS if not already enabled
  ALTER TABLE public.client_points ENABLE ROW LEVEL SECURITY;

  -- Create policy if it doesn't exist
  DROP POLICY IF EXISTS "Service role can manage all points" ON public.client_points;
  CREATE POLICY "Service role can manage all points" ON public.client_points
    FOR ALL USING (true);

  -- Grant permissions
  GRANT ALL ON public.client_points TO service_role;
  GRANT SELECT, INSERT, UPDATE ON public.client_points TO authenticated;

  RETURN 'client_points table ensured successfully';
END;
$$;

-- Grant execute permission to service role
GRANT EXECUTE ON FUNCTION ensure_client_points_table() TO service_role;
