-- COMPREHENSIVE FIX for user creation database errors
-- This addresses the "Database error creating new user" issue

-- Step 1: Fix user_roles table schema completely
DROP TABLE IF EXISTS user_roles CASCADE;

-- Create the correct user_roles table schema
CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);

-- Add comment
COMMENT ON TABLE public.user_roles IS 'Application roles for each user.';

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON public.user_roles(role);

-- Step 2: Enable RLS with correct policies (no infinite recursion)
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Drop any existing policies
DROP POLICY IF EXISTS "Users can view their own role" ON public.user_roles;
DROP POLICY IF EXISTS "Users can insert their own role" ON public.user_roles;
DROP POLICY IF EXISTS "Users can update their own role" ON public.user_roles;
DROP POLICY IF EXISTS "Admins can manage all roles" ON public.user_roles;

-- Create simple, non-recursive policies
CREATE POLICY "Users can view their own role" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own role" ON public.user_roles
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own role" ON public.user_roles
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Step 3: Grant proper permissions
GRANT ALL ON public.user_roles TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.user_roles TO authenticated;

-- Step 4: Ensure auth.users table has proper triggers and functions
-- Check if the trigger function exists for user_roles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- This function will be called when a new user is created
  -- We'll let the application handle role creation explicitly
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Step 5: Check if profiles table exists and is properly configured
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'profiles') THEN
    -- Create profiles table if it doesn't exist
    CREATE TABLE public.profiles (
      id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
      role app_role NOT NULL DEFAULT 'client',
      first_name TEXT,
      last_name TEXT,
      phone TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    -- Enable RLS on profiles
    ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
    
    -- Create policies for profiles
    CREATE POLICY "Users can view their own profile" ON public.profiles
      FOR SELECT USING (auth.uid() = id);
    
    CREATE POLICY "Users can insert their own profile" ON public.profiles
      FOR INSERT WITH CHECK (auth.uid() = id);
    
    CREATE POLICY "Users can update their own profile" ON public.profiles
      FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
    
    -- Grant permissions
    GRANT ALL ON public.profiles TO service_role;
    GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
    
    RAISE NOTICE 'Created profiles table';
  ELSE
    RAISE NOTICE 'Profiles table already exists';
  END IF;
END $$;

-- Step 6: Test the setup
DO $$
BEGIN
  -- Test that we can query user_roles without infinite recursion
  PERFORM 1 FROM public.user_roles LIMIT 1;
  RAISE NOTICE '✅ user_roles table is working correctly';
  
  -- Test that we can query profiles
  PERFORM 1 FROM public.profiles LIMIT 1;
  RAISE NOTICE '✅ profiles table is working correctly';
  
  RAISE NOTICE '🎉 Database setup completed successfully!';
EXCEPTION
  WHEN OTHERS THEN
    RAISE NOTICE '❌ Error during setup: %', SQLERRM;
END $$;
