-- FIX: Create missing client_points table
-- This is causing the "Database error creating new user" issue

-- 1. Create the client_points table
CREATE TABLE IF NOT EXISTS public.client_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  points INTEGER DEFAULT 0 NOT NULL,
  total_earned INTEGER DEFAULT 0 NOT NULL,
  total_redeemed INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 2. Add comment
COMMENT ON TABLE public.client_points IS 'Client points and rewards system';

-- 3. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_client_points_user_id ON public.client_points(user_id);
CREATE INDEX IF NOT EXISTS idx_client_points_points ON public.client_points(points);

-- 4. Enable RLS
ALTER TABLE public.client_points ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS policies
CREATE POLICY "Users can view their own points" ON public.client_points
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own points" ON public.client_points
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Service role can manage all points" ON public.client_points
  FOR ALL USING (true);

-- 6. Grant permissions
GRANT ALL ON public.client_points TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.client_points TO authenticated;

-- 7. Create a function to initialize points for new users
CREATE OR REPLACE FUNCTION initialize_client_points()
RETURNS TRIGGER AS $$
BEGIN
  -- Only create points record for client role users
  IF NEW.raw_user_meta_data->>'role' = 'client' THEN
    INSERT INTO public.client_points (user_id, points, total_earned, total_redeemed)
    VALUES (NEW.id, 0, 0, 0);
  END IF;
  
  RETURN NEW;
EXCEPTION
  WHEN OTHERS THEN
    -- Log error but don't fail user creation
    RAISE WARNING 'Failed to initialize client points for user %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8. Create trigger to initialize points for new users
DROP TRIGGER IF EXISTS initialize_client_points_trigger ON auth.users;
CREATE TRIGGER initialize_client_points_trigger
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION initialize_client_points();

-- 9. Test the fix
DO $$
DECLARE
  test_user_id UUID := gen_random_uuid();
  test_email TEXT := 'test-' || extract(epoch from now()) || '@example.com';
BEGIN
  RAISE NOTICE 'Testing user creation with client_points table...';
  
  -- Test user creation
  INSERT INTO auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at
  ) VALUES (
    '00000000-0000-0000-0000-000000000000',
    test_user_id,
    'authenticated',
    'authenticated',
    test_email,
    crypt('testpassword123', gen_salt('bf')),
    now(),
    '{}',
    '{"role": "client"}'::jsonb,
    now(),
    now()
  );
  
  RAISE NOTICE 'SUCCESS: User created with ID: %', test_user_id;
  
  -- Check if points record was created
  IF EXISTS (SELECT 1 FROM public.client_points WHERE user_id = test_user_id) THEN
    RAISE NOTICE 'SUCCESS: Client points record created';
  ELSE
    RAISE NOTICE 'WARNING: Client points record not created';
  END IF;
  
  -- Clean up
  DELETE FROM public.client_points WHERE user_id = test_user_id;
  DELETE FROM auth.users WHERE id = test_user_id;
  RAISE NOTICE 'Test completed and cleaned up';
  
EXCEPTION
  WHEN OTHERS THEN
    RAISE NOTICE 'FAILED: %', SQLERRM;
    -- Clean up on error
    DELETE FROM public.client_points WHERE user_id = test_user_id;
    DELETE FROM auth.users WHERE id = test_user_id;
END $$;

-- 10. Final status
SELECT 'client_points table created and user creation should work now!' as status;
