-- IMMEDIATE FIX: Run this in Supabase SQL Editor RIGHT NOW
-- This will fix the "Database error creating new user" issue

-- Step 1: Drop the problematic user_roles table
DROP TABLE IF EXISTS public.user_roles CASCADE;

-- Step 2: Create the correct user_roles table schema
CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  UNIQUE (user_id, role)
);

-- Step 3: Add comment
COMMENT ON TABLE public.user_roles IS 'Application roles for each user.';

-- Step 4: Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON public.user_roles(role);

-- Step 5: Enable RLS
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Step 6: Create RLS policies (without infinite recursion)
CREATE POLICY "Users can view their own role" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own role" ON public.user_roles
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own role" ON public.user_roles
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Step 7: Grant permissions
GRANT ALL ON public.user_roles TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.user_roles TO authenticated;

-- Step 8: Test that it works
SELECT 'user_roles table fixed successfully!' as status;
