import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const {
      firstName,
      lastName,
      email,
      password,
      phone,
      termsAccepted
    } = body

    // Validate required fields
    if (!firstName || !lastName || !email || !password || !phone) {
      return NextResponse.json(
        { message: 'Missing required fields' },
        { status: 400 }
      )
    }

    if (!termsAccepted) {
      return NextResponse.json(
        { message: 'Terms acceptance is required' },
        { status: 400 }
      )
    }

    console.log('🚀 Creating trainer registration for:', email)

    // Create Supabase client with service role for admin operations
    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      {
        cookies: {
          getAll() {
            return []
          },
          setAll(cookiesToSet) {
            // No-op for service role client
          },
        },
      }
    )

    // CRITICAL FIX: Ensure client_points table exists before user creation
    console.log('🔧 Ensuring client_points table exists...')
    try {
      await supabase.rpc('ensure_client_points_table')
    } catch (error) {
      console.log('⚠️ Could not ensure client_points table via RPC, trying direct SQL...')
      // Try to create the table directly
      const { error: createTableError } = await supabase
        .from('client_points')
        .select('id')
        .limit(1)
      
      if (createTableError && createTableError.code === '42P01') {
        console.log('📋 Creating client_points table...')
        // Table doesn't exist, create it
        const createTableSQL = `
          CREATE TABLE IF NOT EXISTS public.client_points (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id UUID NOT NULL,
            points INTEGER DEFAULT 0 NOT NULL,
            total_earned INTEGER DEFAULT 0 NOT NULL,
            total_redeemed INTEGER DEFAULT 0 NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(user_id)
          );
          ALTER TABLE public.client_points ENABLE ROW LEVEL SECURITY;
          CREATE POLICY IF NOT EXISTS "Service role can manage all points" ON public.client_points FOR ALL USING (true);
          GRANT ALL ON public.client_points TO service_role;
          GRANT SELECT, INSERT, UPDATE ON public.client_points TO authenticated;
        `
        
        // Execute the SQL directly
        const { error: sqlError } = await supabase.rpc('exec_sql', { sql: createTableSQL })
        if (sqlError) {
          console.log('⚠️ Could not create table via RPC, continuing anyway...')
        } else {
          console.log('✅ client_points table ensured')
        }
      }
    }

    // Check if email already exists
    const { data: existingUser } = await supabase.auth.admin.listUsers()
    const emailExists = existingUser.users.find(user => user.email === email)

    if (emailExists) {
      return NextResponse.json(
        { message: 'Email already registered' },
        { status: 400 }
      )
    }

    // Create auth user with admin client
    const { data: authData, error: authError } = await supabase.auth.admin.createUser({
      email,
      password,
      email_confirm: true, // Skip email confirmation
      user_metadata: {
        first_name: firstName,
        last_name: lastName,
        role: 'trainer'
      }
    })

    if (authError) {
      console.error('❌ User creation failed:', authError)
      return NextResponse.json(
        { message: authError.message || 'Failed to create user account' },
        { status: 400 }
      )
    }

    if (!authData.user) {
      return NextResponse.json(
        { message: 'Failed to create user account' },
        { status: 400 }
      )
    }

    console.log('✅ User created successfully:', authData.user.id)

    // Create user role entry
    const { error: roleError } = await supabase
      .from('user_roles')
      .insert({
        user_id: authData.user.id,
        role: 'trainer'
      })

    if (roleError) {
      console.error('❌ Role creation failed:', roleError)
      // Clean up user
      await supabase.auth.admin.deleteUser(authData.user.id)
      return NextResponse.json(
        { message: 'Failed to create user profile' },
        { status: 500 }
      )
    }

    console.log('✅ User role created')

    // Create trainer profile
    const trainerData = {
      user_id: authData.user.id,
      first_name: firstName,
      last_name: lastName,
      email: email,
      phone: phone,
      hire_date: new Date().toISOString().split('T')[0]
    }

    const { data: trainerRecord, error: trainerError } = await supabase
      .from('trainers')
      .insert(trainerData)
      .select()
      .single()

    if (trainerError) {
      console.error('❌ Trainer profile creation failed:', trainerError)
      
      // Clean up on error
      console.log('🧹 Cleaning up user due to trainer creation failure...')
      await supabase.auth.admin.deleteUser(authData.user.id)
      await supabase
        .from('user_roles')
        .delete()
        .eq('user_id', authData.user.id)
      
      return NextResponse.json(
        { message: `Failed to create trainer profile: ${trainerError.message}` },
        { status: 500 }
      )
    }

    console.log('✅ Trainer profile created successfully')

    // Also create in trainers_legacy table for backward compatibility
    const coachData = {
      user_id: authData.user.id,
      first_name: firstName,
      last_name: lastName,
      email: email,
      phone: phone,
      hire_date: new Date().toISOString().split('T')[0]
    }

    const { error: coachError } = await supabase
      .from('trainers_legacy')
      .insert(coachData)

    if (coachError) {
      console.log('⚠️ Warning: Failed to create coach record:', coachError)
      // Don't fail the whole process if this fails, just log it
    } else {
      console.log('✅ Coach record created for compatibility')
    }

    console.log('🎉 Trainer registration completed successfully!')
    console.log(`📊 Created records:`)
    console.log(`  - Auth user: ${authData.user.id}`)
    console.log(`  - User role: trainer`)
    console.log(`  - Trainer: ${trainerRecord?.id || 'unknown'}`)

    return NextResponse.json({
      success: true,
      message: 'Trainer registration successful! You can now log in.',
      user: {
        id: authData.user.id,
        email: authData.user.email,
        role: 'trainer',
        status: 'active'
      },
      trainer: trainerRecord
    })

  } catch (error) {
    console.error('❌ Trainer registration error:', error)
    return NextResponse.json(
      { message: 'Internal server error' },
      { status: 500 }
    )
  }
}