-- COMPREHENSIVE DATABASE FIX
-- This will fix all the issues preventing user creation
-- Run this in Supabase SQL Editor

-- 1. First, let's check what tables exist
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_name LIKE '%client%' OR table_name LIKE '%points%';

-- 2. Drop any existing client_points table to start fresh
DROP TABLE IF EXISTS public.client_points CASCADE;

-- 3. Create the client_points table
CREATE TABLE public.client_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  points INTEGER DEFAULT 0 NOT NULL,
  total_earned INTEGER DEFAULT 0 NOT NULL,
  total_redeemed INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 4. Add comment
COMMENT ON TABLE public.client_points IS 'Client points and rewards system';

-- 5. Create index
CREATE INDEX idx_client_points_user_id ON public.client_points(user_id);

-- 6. Enable RLS
ALTER TABLE public.client_points ENABLE ROW LEVEL SECURITY;

-- 7. Create policies
DROP POLICY IF EXISTS "Service role can manage all points" ON public.client_points;
CREATE POLICY "Service role can manage all points" ON public.client_points
  FOR ALL USING (true);

-- 8. Grant permissions
GRANT ALL ON public.client_points TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.client_points TO authenticated;

-- 9. Check if there are any triggers on auth.users that might be causing issues
SELECT 
  trigger_name, 
  event_manipulation, 
  action_statement 
FROM information_schema.triggers 
WHERE event_object_table = 'users' 
AND event_object_schema = 'auth';

-- 10. Check for any functions that might be trying to insert into client_points
SELECT 
  routine_name, 
  routine_definition 
FROM information_schema.routines 
WHERE routine_definition LIKE '%client_points%' 
AND routine_schema = 'public';

-- 11. Verify the table was created
SELECT 'client_points table created successfully!' as status;
SELECT COUNT(*) as table_exists FROM information_schema.tables 
WHERE table_name = 'client_points' AND table_schema = 'public';