-- ULTRA SIMPLE FIX: Create client_points table without foreign key
-- Run this in Supabase SQL Editor

-- Drop table if exists to start fresh
DROP TABLE IF EXISTS public.client_points CASCADE;

-- Create the client_points table without foreign key constraint
CREATE TABLE public.client_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  points INTEGER DEFAULT 0 NOT NULL,
  total_earned INTEGER DEFAULT 0 NOT NULL,
  total_redeemed INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Add comment
COMMENT ON TABLE public.client_points IS 'Client points and rewards system';

-- Create index
CREATE INDEX idx_client_points_user_id ON public.client_points(user_id);

-- Enable RLS
ALTER TABLE public.client_points ENABLE ROW LEVEL SECURITY;

-- Create basic policy
CREATE POLICY "Service role can manage all points" ON public.client_points
  FOR ALL USING (true);

-- Grant permissions
GRANT ALL ON public.client_points TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.client_points TO authenticated;

-- Test that the table exists
SELECT 'client_points table created successfully!' as status;
